### ISSUE TITLE
Use case example?

### ISSUE THREAD

**Issue by bill-o-more** [flodlc/ts-fastify-client#1]
Hi,

This project looks really interesting, but there's something I miss. 
As far as I see from the readme (and sorry if it's a noob question), you wrap standard fastify+typebox schema definitions, so you could use them to type-safely get data from the final endpoint you declare separately; but what is its use case, if both endpoint declaration and gettiong data from it reside on the same, server, side?

**Comment by flodlc** [comment]
Hi @bill-o-more, it's made to be used in a monorepo or to be published on npm.
Let's say you have a monorepo with 3 packages

monorepo:
- server
- apiClient
- webapp

typebox-client is used in this case to create the api client which is used in the webapp.
