### ISSUE TITLE
Usage with @fastify/autoload possible?

### ISSUE THREAD

**Issue by sbreiler** [flodlc/ts-fastify-client#8]
Hey, thanks for the plugin! Do you think it is possible to use this in combination with the autoload plugin?

I used `fastify generate server --esm --lang=ts --standardlint` which essentially generate this file [https://github.com/fastify/fastify-cli/blob/master/templates/app-ts-esm/src/app.ts](https://github.com/fastify/fastify-cli/blob/master/templates/app-ts-esm/src/app.ts)

**Comment by flodlc** [comment]
Hi @sbreiler !
Didn't try but I don't see any reasons, did you try and have an issue with it ?

**Comment by sbreiler** [comment]
Yeah, i tried several things. The indirect way of creating a fastify server through fastify-cli is strange enough on its own, also how would you rewrite the route registration shown here [https://github.com/fastify/fastify-cli/blob/master/templates/app-ts-esm/src/routes/root.ts](https://github.com/fastify/fastify-cli/blob/master/templates/app-ts-esm/src/routes/root.ts)?

My attempt looks like this:
```typescript
import { z } from 'zod';
import {FastifyInstance} from 'fastify'
import {createRoute} from '@http-wizard/core'


const getRoot = async (fastify: FastifyInstance) => createRoute(
    '/',
    {
      method: 'GET',
      schema: {
          response: {
              200: z.object({
                  root: z.boolean()
              })
          }
      },
    }
).handle((props) => {
    fastify.route({
        ...props,
        handler: () => ({root:true})
    })
})

export default getRoot
```

I'm a bit lost here and new to fastify. Maybe i gonne try to create a script which gets my routes and writes a defintion file for me (which could be automatically executed by some watcher).

**Comment by sbreiler** [comment]
Hi,

just letting you know, i moved onto another solution.

Thanks again

**Comment by VxRain** [comment]
> Hi,
> 
> just letting you know, i moved onto another solution.
> 
> Thanks again

Hey, guy. So what is your final solution?

**Comment by 7iomka** [comment]
> Hi,
> 
> just letting you know, i moved onto another solution.
> 
> Thanks again

Would you share the solution you switched to?

**Comment by sbreiler** [comment]
Unfortunately I don't know anymore, I was in an experimental phase to test different frameworks as a whole. I'm currently trying remix.
